service: cesar-prueba-backend
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-offline
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  timeout: 120
  iam:
    role: arn:aws:iam::319643186591:role/omnichannel-lambda-access-desa-role
  deploymentBucket:
    name: ${self:custom.settings.${opt:stage}.env.deployBucket}
    serverSideEncryption: AES256
  apiGateway:
    restApiId: ${self:custom.settings.${opt:stage}.env.apiId}
    restApiRootResourceId: ${self:custom.settings.${opt:stage}.env.apiRootResourceId}
  environment: # Variables de entorno globales
    SWAPI_API_URL: ${self:custom.settings.${opt:stage, 'dev'}.env.SWAPI_API_URL}
    DB_HOST: ${self:custom.settings.${opt:stage, 'dev'}.env.DB_HOST}
    DB_NAME: ${self:custom.settings.${opt:stage, 'dev'}.env.DB_NAME}
    DB_PASSWORD: ${self:custom.settings.${opt:stage, 'dev'}.env.DB_PASSWORD}
    DB_USERNAME: ${self:custom.settings.${opt:stage, 'dev'}.env.DB_USERNAME}

custom:
  stage: ${opt:stage, self:provider.stage}
  settings:
    dev:
      deployBucket: omnichannel-dev-lambda
      env:
        SWAPI_API_URL: ${env:SWAPI_API_URL}
        DB_HOST: ${env:DB_HOST_DEV}
        DB_NAME: ${env:DB_NAME_DEV}
        DB_PASSWORD: ${env:DB_PASSWORD_DEV}
        DB_PORT: ${env:DB_PORT_DEV}
        DB_USERNAME: ${env:DB_USERNAME_DEV}
        apiId: ${env:apiId}
        apiRootResourceId: ${env:apiRootResourceId}
        deployBucket: ${env:deployBucket}

    prod:
      env:
        SWAPI_API_URL: ${env:SWAPI_API_URL}
        DB_HOST: ${env:DB_HOST_PROD}
        DB_NAME: ${env:DB_NAME_PROD}
        DB_PASSWORD: ${env:DB_PASSWORD_PROD}
        DB_PORT: ${env:DB_PORT_PROD}
        DB_USERNAME: ${env:DB_USERNAME_PROD}
        apiId: ${env:apiId}
        apiRootResourceId: ${env:apiRootResourceId}
        deployBucket: ${env:deployBucket}
  prune:
    automatic: true
    number: 1
        


functions:
  api:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: 'reto-tecnico-indra/{proxy+}'
          cors: true
  
