export const tranlationGetVehicleMap = {
    name: "nombre",
    model: "modelo",
    vehicle_class: "clase_vehiculo",
    manufacturer: "fabricante",
    length: "longitud",
    cost_in_credits: "costo",
    crew: "personal",
    passengers: "pasajeros",
    max_atmosphering_speed: "velocidad_maxima",
    cargo_capacity: "capacidad_maxima_peso",
    consumables: "consumibles",
    films: "peliculas",
    pilots: "pilotos",
    url: "url",
    created: "fecha_creacion",
    edited: "fecha_edicion",
}